<?php

include "connection_openDB.php";
include "connection_closeDB.php";
include "getData.php";

$db = connectDB();

session_start();

session_cache_limiter('private, must-revalidate');

$_SESSION['views']=1;

$ses_id = session_id(); 

?>

<html>

<head>
  <style>

  a{
    text-decoration:none;
  }

 .container {
    position: absolute;
    top: 10px;
    left: 180px;
    width: 900px;
    height: 800px;
    padding: 5px;
    /*border-left: 1px solid;  
    border-right: 1px solid; */ 
 }

 #img{
    position: absolute;
    top:-20%;
    left: -1%;
  }

  </style>
  <link rel="stylesheet" type="text/css" href="css/style.css?n=1">
  <script type="text/javascript" src="javascript/standard/jquery-2.0.3.min.js"></script>
</head>

<body>

<?php

$filesize =  ini_get('upload_max_filesize');

?>

<div class="container">

<div id="img">
<img src="images/mat_2.png" alt="Matryoshka">
</div>

<div id="desp">
<p> Visualizer for XML files generated by the <a href="http://eshare.verigy.net/display/93KSystem/PerformanceInstrumentation"  target="_blank" >PerformanceInstrumentation</a> component<p>
</div>

<div id='uploadFile'>
<form name="uploadfile" action="" method="post" enctype="multipart/form-data">
<label for="file">Select a file (max size <?php echo $filesize; ?>B)</label>
<input type="file" name="file" id="file"><br>
<input type="submit" name="submit" value="Upload">

<input id='infile' type='text' name='rename' value='' maxlength='100'/> <br/>

</form>
</div>

<?php 


if(isset($_SESSION['views'])){
$_SESSION['views']=$_SESSION['views']+1;
//echo "Views=". $_SESSION['views']."<br>";
}

//echo $ses_id."<br>";

$allowedExts = array("xml");
$temp = explode(".", $_FILES["file"]["name"]);
$extension = end($temp);

//echo "This is the temp:" . $temp . "\n";
 
//echo "This is the extension:" . $extension . "\n";

//echo "This is the type of file : ";
//echo $_FILES["file"]["type"] . "\n";

if($_FILES["file"]["type"]){

if (($_FILES["file"]["type"] == "text/xml")
&& ($_FILES["file"]["size"] < 50000000)
&& in_array($extension, $allowedExts))
{
  
  echo "Reached here";

  if ($_FILES["file"]["error"] > 0)
    {
    echo "Error: " . $_FILES["file"]["error"] . "<br>";
    }
  else{
    //echo "Upload: " . $_FILES["file"]["name"] . "<br>";
    //echo "Type: " . $_FILES["file"]["type"] . "<br>";
    //echo "Size: " . ($_FILES["file"]["size"] / 1024) . " kB<br>";
    //echo "Stored in: " . $_FILES["file"]["tmp_name"];
  
    //echo "Reached inside the loop";
 
    if(file_exists("input/" . $_FILES["file"]["name"]) && $_POST["rename"])
    {

       //echo "Reached in file existing loop";    
     
       $newFileName = $_POST["rename"].".xml";
       
       $moved = move_uploaded_file($_FILES["file"]["tmp_name"],"input/" . $newFileName );

       echo "<div id='sucess'><p>The uploaded file is saved as</p>" . $newFileName . "</div>";
   
    }elseif (file_exists("input/" . $_FILES["file"]["name"]))
      {

       //echo "Reached in file not existing loop";     

       $filename = $_FILES["file"]["name"];

       if($filename){
          //echo "<label id='infile'>Enter the filename:</label>";
          echo " <p id='place1'>File with same name exists. Select the file again and enter new name without extension.</p>";
          echo "<script>";
          echo " document.getElementById('infile').style.visibility = 'visible';";
          echo "</script>";
          //echo " <input id='infile' type='text' name='rename' value='' maxlength='100'/> <br/>";
          //echo "<input type='submit' name='submit'>";
          //echo "</form>";
        }

     }
     else{
 
       // echo "Reached in move new file loop";     
       
        $filename = $_FILES["file"]["name"];    
        $moved = move_uploaded_file($_FILES["file"]["tmp_name"],"input/" . $filename );  

        echo "<div id='sucess'><p>The uploaded file is saved as</p>" . $filename . "</div>";
       
     } 

  }
}
else
  {
  echo "<div id='error'><p>Invalid file </p></div>";
  }

}

?>

<script>
    function submitForm(action)
    {
        if( action == "fileselector_db.php"){
           
           document.getElementById('fileList').action = action;
           //document.getElementById('fileList').target = "_blank";
           document.getElementById('fileList').submit();

        }else{

           if(confirm("Are you sure you want to delete this file?")){
              document.getElementById('fileList').action = action;
              document.getElementById('fileList').submit();     
           }

        }

    }

    function submitVisForm(action){

         if( action == "visualize.php"){
           
           document.getElementById('fileVisList').action = action;
           document.getElementById('fileVisList').target = "_blank";
           document.getElementById('fileVisList').submit();

        }else{

           if(confirm("Are you sure you want to delete this file?")){
              document.getElementById('fileVisList').action = action;
              document.getElementById('fileVisList').submit();     
           }

        }

 
    }

    function showProgress(){
  
        //setTimeout(function() {
        
         /*$.get("fileselector_db.php", {"submit_button":Parse }, function(data) {
           //$("#progressbar").progressbar({
                alert (data);
            //});
         });*/

         alert("reached here");

         /*$.ajax({
            type: "POST",
            url: "fileselector_db.php",
            data: {"submit_button":Parse}
            //dataType:"text"     
          })
            .done(function (result){

               alert(result);
               
            });*/

        //}, 3000);
    }

   
</script>

<div id='selectFile'>

 <form id="fileList" action=""  method="post">
 <label for = "file" >Choose a file to Parse</label>
 <br>
 <!--<select  size="4" name="filename[]" multiple="multiple">-->
 <select  size="4" name="filename" multiple="multiple">
    
 <?php 
   
    populateSelect();
   
    //check for the number of files in input folder 
    function populateSelect(){

     if ($handle = opendir('input')) {
       while (false !== ($file = readdir($handle)))
       {
          if (($file != ".") 
          && ($file != ".."))
          {
            $val = "input/" . $file;
            $thelist = '<option value="'.$val.'" />'.$file.'</option>';
            echo $thelist;
          }
       }

       closedir($handle);
     }
   
    }

  ?>

 </select>
 <br>
 <label>Description:</label>
 <input type="text" name="desc" id="desc">
 <input name="submit_button" type="submit" onclick="submitForm('fileselector_db.php')" value="Parse">
 <input name="submit_button" type="submit" onclick="submitForm('deleteFile_db.php')" value="DeleteFile">

 </form>

</div>

<div id='selectFileDB'>

 <form id="fileVisList" action=""  method="post">
 <label for = "file" >Choose a file to Visualize</label>
 <br>

 <select id="file_list" size="6" name="filename" multiple="multiple">
 </select>

  <script>
  data_files = <?php getfiles($db,$files_array); ?>
 
  //console.log(data_files);

  for ( var i = 0; i < data_files.length; i++ ){
             $('#file_list').append($("<option/>", {
              value:data_files[i].file_id + "|" + data_files[i].filename + "|" + data_files[i].desc,
              text: data_files[i].file_id + "|" + data_files[i].filename + "|" + data_files[i].desc
             }));
     }

  </script>


<select name="vis"> 
     <option value="all" />All</option>
     <!--<option value="overhead" />Overhead</option>-->
     <option value="tree" />CallTree</option>
     <option value="concurrent" />Concurrency</option>
 </select>

<!--<input name="submit_button" type="submit" value="Visualize">-->

<input name="submit_button" type="submit" onclick="submitVisForm('visualize.php')" value="Visualize">
 
<br>

<input name="submit_button" type="submit" onclick="submitVisForm('deleteDBentry.php')" value="Delete from Database">

</form>

</div>

<!--
<div id="compareFile">

<form action="fileselector.php"  method="post" target="_blank">
 <label for = "filename" >Choose files to compare</label>
 <br>
 <p>Ref file</p>
 <select  size="4" name="refFilename" >

 <?php 
    //populateSelect();
 ?>

 </select>

 <select  size="4" name="compfilename" >
  
 <?php 
    //populateSelect();
 ?>
 
 </select>

 <select size="2" name="comparevis" > 
     <option value="all" />Detailed</option>
     <option value="heatmap" />HeatMap</option>
 </select>

 <input name="submit" type="submit" value="Compare">
 </form>

</div>
-->

<div id="tested">
<p> Tested on firefox version 17.0.1</p>
</div>

<div id="help">
<p> Questions and Support:Anukiran.Solur@advantest.com</p>
</div>
  
</div>

</body>
</html>  

<?php 

closeDB($db);

?>